package com.vi.tenantservice.api.exception.httpresponse;

public enum HttpStatusExceptionReason {
  SUBDOMAIN_NOT_UNIQUE,
  NOT_ALLOWED_TO_CHANGE_SUBDOMAIN,
  NOT_ALLOWED_TO_CHANGE_LICENSING,
  NOT_ALLOWED_TO_CHANGE_SETTING,

  NOT_ALLOWED_TO_CHANGE_LEGAL_CONTENT,

  LANGUAGE_KEY_NOT_VALID,

  ID_MUST_BE_NULL_WHEN_CREATING_TENANT,
  SUBDOMAIN_IN_REQUEST_BODY_NOT_EQUAL_TO_SUBDOMAIN_IN_URL,

  LANGUAGE_MUST_BE_NON_NULL_AND_PROPER_LENGTH,
}
